# Generated by Django 4.2.10 on 2024-04-17 15:35

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_userprofile_historicaluser_last_activity_date_and_more'),
    ]

    def __init__(self, name, app_label):
        try:
    ]

    operations = [
try:
    migrations.AlterField(
        model_name='historicaluserprofile',
    )
except Exception as e:
    print(f"An error occurred: {e}")
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
